platform :ios, '13.4'

require 'json'

def get_env_variable(name)
  env_file = File.join(__dir__, '..', '.env')
  if File.exist?(env_file)
    File.foreach(env_file) do |line|
      if line.strip.start_with?("#{name}=")
        return line.split('=', 2)[1].strip
      end
    end
  end
  return ENV[name]
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

target 'famMeal' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'MapboxMaps', '~> 10.18.2'

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    react_native_post_install(installer)
    
    # Use the token to configure the Mapbox downloads URL
    mapbox_token = get_env_variable('MAPBOX_DOWNLOADS_TOKEN')
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['MAPBOX_DOWNLOADS_TOKEN'] = mapbox_token
      end
    end
  end
end

target 'famMealTests' do
  inherit! :complete
  # Pods for testing
end
